CREATE TABLE IF NOT EXISTS cars (
    symboling INTEGER,
    CarName VARCHAR(255),
    fueltype VARCHAR(50),
    aspiration VARCHAR(50),
    doornumber INTEGER,
    carbody VARCHAR(50),
    drivewheel VARCHAR(50),
    enginelocation VARCHAR(50),
    wheelbase REAL,
    carlength REAL,
    carwidth REAL,
    carheight REAL,
    curbweight REAL,
    enginetype VARCHAR(50),
    cylindernumber INTEGER,
    enginesize INTEGER,
    fuelsystem VARCHAR(50),
    boreratio REAL,
    stroke REAL,
    compressionratio REAL,
    horsepower INTEGER,
    peakrpm INTEGER,
    citympg INTEGER,
    highwaympg INTEGER,
    price REAL,
    model VARCHAR(255)
);
